---
title: "modelos_aditivos"
author: "Gonzalo Chebi"
date: "28/6/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
set.seed(123)
n = 5000
x = runif(n)
mu = sin(2*(4*x-2)) + 2*exp(-(16^2)*((x-.5)^2))
y = rnorm(n, mu, .3)
d = data.frame(x,y) %>% 
  mutate(categoria = factor(rpois(n, 2)))
```

```{r}
d_train = d[1:(n * 1/10), ]
d_test = d[(n * 1/10 + 1):n, ]
```

```{r}
d_train %>% 
  ggplot(aes(x, y)) + geom_point()
```

```{r}
library(mgcv)
fit_1 = gam(y ~ x, data = d_train)
fit_1 %>% summary()
```

```{r}
plot_predictions = function(fit, test_data){
  preds = predict(fit, test_data)
d_test %>% 
  mutate(preds_fit = preds) %>% 
  pivot_longer(c(y, preds_fit)) %>% 
  ggplot(aes(x = x, color = name, y = value)) +
  geom_point()
}

get_prediction_error = function(fit, test_data){
  preds = predict(fit, test_data)
  mean((preds - test_data$y)**2)
}
```

```{r}
fit = gam(y ~ x, data = d_train)
plot_predictions(fit, d_test)

```

```{r}
print(get_prediction_error(fit, d_test))

```

```{r}
fit = gam(y ~ s(x, k = 5, sp = 0, bs = 'cr'), data = d_train) 
# k=4 es la cantidad de grados de libertad dado por la cantidad de nodos
# sp = 0 es el lambda de penalizacion
# bs indica el espacio de funciones que quiero usar (cr = cubic regression splines)
plot_predictions(fit, d_test)

```

```{r}
print(get_prediction_error(fit, d_test))

```

```{r}
fit %>% summary()
```

```{r}
fit = gam(y ~ s(x, k=10, sp=0, bs = 'cr'), data = d_train) 
plot_predictions(fit, d_test)


# al no pasar sp, estima el sp (lambda) usando el que minimice GCV.

```

```{r}
fit = gam(y ~ s(x, k=10, bs = 'cr'), data = d_train) 
plot_predictions(fit, d_test)
```

```{r}
print(get_prediction_error(fit, d_test))

```

```{r}
fit %>% summary()
```

```{r}
fit = gam(y ~ s(x, k = 21, bs = 'cr', sp=0), data = d_train)
plot_predictions(fit, d_test)

```

```{r}
print(get_prediction_error(fit, d_test))

```

```{r}
fit %>% summary()
```

```{r}
fit = gam(y ~ s(x, k = 100, sp=0, bs = 'cr'), data = d_train)
plot_predictions(fit, d_test)

print(get_prediction_error(fit, d_test))
```

```{r}
fit = gam(y ~ s(x, k = 500, bs = 'cr'), data = d_train)
plot_predictions(fit, d_test)

```

```{r}
print(get_prediction_error(fit, d_test))

```

```{r}
fit = gam(y ~ s(x, bs = 'cr'), data = d_train) #toma por default k=10
plot_predictions(fit, d_test)

print(get_prediction_error(fit, d_test))
```

```{r}
fit = gam(y ~ s(x, k = 100, bs = 'cr') + s(categoria, bs = 're'), data=d_train)
plot_predictions(fit, d_test)

print(get_prediction_error(fit, d_test))
```

```{r}
fit %>% summary()
```

```{r}
library(visreg)
fit = gam(y ~ s(x, k = 100, bs = 'cr') + s(categoria, bs = 're'), data = d_train)
visreg(fit)
```
